default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  user: eficiencia_energetica
  password: password

development:
  <<: *default
  database: eficiencia_energetica_development

test:
  <<: *default
  database: eficiencia_energetica_test
